# Change these first
owner: halyul # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Server Eagle
    url: $SERVER_EAGLE
  - name: Server Eagle 1
    check: "tcp-ping"
    url: $SERVER_EAGLE_1
    port: 80
  - name: Server Goose
    url: $SERVER_GOOSE
  - name: Server Cat
    url: $SERVER_CAT

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.xhy.ch
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: Homepage
      href: https://xhy.ch

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
